"""criacao do pedido de refeicao

Revision ID: dbf6327f155b
Revises: fef5dd3e06ce
Create Date: 2026-04-29 21:44:08.252458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf6327f155b'
down_revision = 'fef5dd3e06ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=30), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('enviado_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('quantidade_envios', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos_refeicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_refeicao_numero_pedido'), ['numero_pedido'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_refeicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_refeicao_numero_pedido'))

    op.drop_table('pedidos_refeicao')
    # ### end Alembic commands ###
