"""consumo individual do pedido de refeicao

Revision ID: ea31abfc7d31
Revises: dbf6327f155b
Create Date: 2026-04-29 22:50:10.211088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea31abfc7d31'
down_revision = 'dbf6327f155b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumos_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('item_cardapio_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['item_cardapio_id'], ['itens_cardapio.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_refeicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumos_refeicao')
    # ### end Alembic commands ###
