"""cadastro de colaboradores e equipes

Revision ID: f757a734568c
Revises: e28b6fa8730c
Create Date: 2026-04-29 14:31:43.280635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f757a734568c'
down_revision = 'e28b6fa8730c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaboradores_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_colaboradores_matricula'), ['matricula'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaboradores_matricula'))
        batch_op.drop_index(batch_op.f('ix_colaboradores_cpf'))

    op.drop_table('colaboradores')
    op.drop_table('equipes')
    # ### end Alembic commands ###
